### ISSUE TITLE
Upgrade to new release of DRS Batch Builder client

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/drs-deposit#108]
From Vitaly on July 20th:

_A new release of DRS Batch Builder client is available for [download](https://drive.google.com/file/d/1V3lnoIPSM3KJNsl6mgfsanmejDY17F_o). The new version of Batch Builder (2.2.21) introduces support for Java OpenJDK 11 and removes support for Oracle Java 8 (an older version of Java). Instructions for installing the new version (including a link to download Java OpenJDK 11) are available [here](https://wiki.harvard.edu/confluence/display/LibraryStaffDoc/1.+Installation+and+Setup)._

**Comment by jimk-bdrc** [comment]
Upgrade to 2.3

**Comment by jimk-bdrc** [comment]
Using `/home/DRS` as build root. (owner: jimk:service)
