### ISSUE TITLE
Create test batch of 50 works for DRS

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/drs-deposit#117]
Create a MARC file of 50 works that have not been put into DRS yet, and send to Corinna Baksis. She will enter them into the DRS QA system, and we can build batches against them.

**Comment by jimk-bdrc** [comment]
@eroux can you please provide the query that returns the list of works (default pageSize=50000) that should go to DRS?[ The existing query](https://purl.bdrc.io/query/table/AO_should_upload_to_DRS?R_RES=bdr:W22084)
indicates a single work's inclusion. But a total list is needed.

**Comment by eroux** [comment]
The existing query should be https://purl.bdrc.io/query/ask/AO_should_upload_to_DRS?R_RES=bdr:W22084 (`ask`, not `table`, it returns a boolean), here's a new query:

https://purl.bdrc.io/query/table/AO_mustbeinDRS

the API hasn't changed, if you want the one csv file with everything:

https://purl.bdrc.io/query/table/AO_mustbeinDRS?&format=csv&pageSize=50000

**Comment by jimk-bdrc** [comment]
Created `DRS.works_for_drs_2023` which is the output of the query. Filter out those already in DRS (which have a HOLLIS id) and those that have not been syncd (WorkImageFileCount = 0):


```sql
select *
from Works w
         inner join works_for_drs2023 wid on wid.WorkName = w.WorkName
where w.HOLLIS is null
  and WorkImageFileCount <> 0;

```
