### ISSUE TITLE
Batch Builder Multi page TIFF

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/drs-deposit#15]
Some images throw this error in Batch Builder. The batch gets built. The file shows as a member in paged data set's descriptor.xml.

Happens in work W00EGS1016782, and others.

Get Vitaly's comments, determine if this will impede ingestion.

[JHoveFitsError.txt](https://github.com/BuddhistDigitalResourceCenter/drs-deposit/files/1572689/JHoveFitsError.txt)

**Comment by TBRC-JimK** [comment]
Hi Vitaly, We’re ramping up to do multiple simultaneous batch builds, there are a couple of questions about Batch Builder based on what we’ve seen in its error logs

1.	It seems we can’t control log4j in fits. The output says it will write fits.log, which it does, in the right place, but it is always 0 length. It’s not absolutely essential, but any guidance you could give on configuring Batchbuilder’s log4j will help us once we start to encounter errors.
2.	On some specific files, we encounter the error in the attached file. Something in JHove is throwing an exception. We see this in about one out of every 20 batches, on one specific file. I’ve attached one such file and the log fragment of the error that file generates. 
The error does not halt the build, and the file appears in the PDS descriptor.xml (attached)
I haven’t completely categorized it, but it seems to only happen on the first image. I’ll gather some more data and try to categorize it. Is this something likely to impact the ingestion?

Thanks,

Jim Katz
Buddhist Digital Resource Center
jimk@tbrc.org
+1 781.254.7537
[I01JW300001__001.tif.err.txt](https://github.com/BuddhistDigitalResourceCenter/drs-deposit/files/1572773/I01JW300001__001.tif.err.txt)
[JHoveFitsError.txt](https://github.com/BuddhistDigitalResourceCenter/drs-deposit/files/1572774/JHoveFitsError.txt)

**Comment by xristy** [comment]
thanks for posting.

**Comment by TBRC-JimK** [comment]
[W00EGS1016782-I01JW30--I01JW300001__0001.zip](https://github.com/BuddhistDigitalResourceCenter/drs-deposit/files/1572776/W00EGS1016782-I01JW30--I01JW300001__0001.zip)

**Comment by TBRC-JimK** [comment]
Vitaly's response

**Comment by xristy** [comment]
We do not intend to have multipage tiffs. The example is the initial page generated by the scan request wizard which has no logic for creating multipage tiffs.

Perhaps it is the result of some sort of corruption. 

In any event it would be good to see if you can test the image verify that it really is multipage or a misreport from jhove fits. 

Since the image can not be correctly deposited as is, it needs to be corrected. Travis may be helpful in figuring out an effective correction. 

One idea might be to collect lists of images needing corrections that could then be batched to update the office archives and the S3.

**Comment by jeffwallman** [comment]
Maybe Travis can do a test on W00EGS1016782 and others.  If we can get a list we can investigate. W00EGS1016782 is a work from early on in the scan request process in 2006. So maybe there is a corruption.

**Comment by TBRC-JimK** [comment]
I see these errors as I process, so I can filter my output as I go along to feed the list of files. I looked up how to detect a multipage tiff, and there are other command line tests that someone can use against the raw data. If Travis has a hard deadline, I could write that script to get the list, and feed the results to him.

 

Jim Katz

Buddhist Digital Resource Center

 <mailto:jimk@tbrc.org> jimk@tbrc.org

+1 781.254.7537

**Comment by TBRC-Travis** [comment]
From our discussion today - we will let the batch building process uncover these multi-page tif issues and determine how many files in the archive fall into this category.  If there ends up being a small number of these files to fix (which we imagine there are) we'll just handle them on a case-by-case basis.  In the case of W00EGS1016782 where the first page of the scan request file extends into a second page we'll likely just want to merge these page together and leave the second page as a blank image which is our usual standard.

**Comment by TBRC-JimK** [comment]
Travis, I think Vitaly has validated that plan. Here's his most recent email to me. I read it as saying they'll just gather the metadata from the first page, and skip the second page, which you should be blanking out.

> Jim,
We ran the additional images through FITS and confirmed that the issue occurs with all three multi-page TIFFs you provided for our testing. We will modify FITS to generate metadata only for the first sub-file in such a TIFF to avoid the issue of duplicate image metadata values that has been causing the error. However, in the meantime, for any multi-page TIFFs in the BDRC collection, we recommend that you extract the sub-files into separate single-page TIFF files before these are processed for DRS ingest. DRS delivery services will only display the first page of a multi-page BW bitonal TIFF.

**Comment by xristy** [comment]
We won't be submitting multi-page tiffs to Harvard.

Once you have a list of problem images to be corrected then Travis will assess.

Assuming that the images are all the initial image of a volume - i.e., what is supposed to be the single page of tbrc metadata - then when the two pages are coalesced into a single image as Travis has discussed there will be no issue with the archive since the multi-page image has appeared as a single image all along.

**Comment by TBRC-JimK** [comment]
Actually fixing multi-page TIFFs assigned to Travis @TBRC-Travis

**Comment by TBRC-JimK** [comment]
I added the "waiting," because it is waiting on more batches being built to find more files. It is very rare

**Comment by TBRC-JimK** [comment]
Created Python script to filter errors and generate paths from errors found in batch builder console logs. The resulting errors (from about half of BDRC's collection) are at this [Google Doc Spreadsheet](https://drive.google.com/open?id=1kKhKeFl_4hacfZ7O6UpLSSRYvBBsSn52KJ4rhRmHHZ4)

**Comment by jimk-bdrc** [comment]
DRS won't see these as a problem, and the offenders have all been fixed.
