### ISSUE TITLE
Remove PDF files from source image directories

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/drs-deposit#21]
Batch Builder does not allow 
* PDF 
* PNG

files to be images  in Paged Data Objects. Some works have them and they should be removed. Travis, do you need specifics, or could you just use `find xx -name \*pdf -prune` or equivalent?

**Comment by TBRC-JimK** [comment]
Added PNG files as well.

**Comment by jimk-bdrc** [comment]
Fixed in #86d635f
