### ISSUE TITLE
Build list of works with outlines

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/drs-deposit#37]
Like #39, but for outlines
1. Except that we dont use disk for outlines we use the query `https://www.tbrc.org/public?module=outline&query=outlines` and capture the output. 
2. Parse it into discrete text files.
3. Batch the text files into one batch, (? What content type?)

Populate xmeru db "test.Outlines" using FK into "test.works" We need this to begin processing works which do not have outlines or print masters.

**Comment by TBRC-JimK** [comment]
In QA, 23 08 18
