### ISSUE TITLE
Build list of print masters

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/drs-deposit#39]
1. See /Volumes/Archive/Wxxx/prints. 
2. Get list of works with prints and write that to db.
3. Start uploading works without prints, and without outlines (see #37)
4. Build batch objects of prints. They're not PDS, because they're PDF files. What are they?

**Comment by TBRC-JimK** [comment]
In QA, db 23 Aug 2018

**Comment by jimk-bdrc** [comment]
We're skipping printmasters and outlines for now.
