### ISSUE TITLE
GetReadyWorks pulls some Volumes which are already uploaded into DRS

### ISSUE THREAD

**Issue by TBRC-TimB** [buda-base/drs-deposit#76]
running `getReadyWorks -d prod:~/.drsBatch.config -n 200 ./20200506ReadyWorks`
should have pulled all works which have not been queued. 
Instead it pulls the same list each time. 

When this list is compared to the most recent list of uploads in DRS, we find that one of the volumes was already uploaded. 

awk script used to make the comparison
`awk 'FNR==NR{a[$3]=$0;next} $2 in a{print a[$2]}' 20200506ReadyWorks 2020-04-28BDRCCumulativeProdDeposits.csv `
matching lines:
`W22677,015327199,W22677-I1KG1714,,`

Line where this Volume Number appears in CumulativeProdDeposit
`452058056,W22677-I1KG1714,"urn-3:FHCL:37290901, urn-3:HUL.DRS.OBJECT:37290900",Buddhist Digital Resource Center,FHCL.COLL,FHCL.COLL.TBRC_0001,PDS DOCUMENT,,batchW22677-1-9d,521675,298,,R,"skyes pa'i rabs kyi rgyud slob dpon dpa' bos mdzad pa, skyes rabs so bzhi pa, jatakamala, སྐྱེས་པའི་རབས་ཀྱི་རྒྱུད་སློབ་དཔོན་དཔའ་བོས་མཛད་པ།",Tibetan Buddhist Resource Center,81411676
`

Sample files I was working from. Converted to .txt so that can be uploaded.
[2020-04-28BDRCCumulativeProdDeposits.txt](https://github.com/buda-base/drs-deposit/files/4588632/2020-04-28BDRCCumulativeProdDeposits.txt)

[20200506ReadyWorks.txt](https://github.com/buda-base/drs-deposit/files/4588634/20200506ReadyWorks.txt)

**Comment by jimk-bdrc** [comment]
Please to close
