### ISSUE TITLE
Move batches from bodhi to druk for upload

### ISSUE THREAD

**Issue by TBRC-TimB** [buda-base/drs-deposit#79]
Attached is a list of built batches that are ready to be moved off of bodhi to druk for upload to Harvard. all batches can be found under /home/timb/DRS_Builds/prod/batchBuilds

**Comment by TBRC-TimB** [comment]
[batchlist.txt](https://github.com/buda-base/drs-deposit/files/4772606/batchlist.txt)

**Comment by jimk-bdrc** [comment]
parallel is so cool. Underway now.

**Comment by jimk-bdrc** [comment]
Done. Now in batchBuilds
