### ISSUE TITLE
DRS Batch Building June 22- 27

### ISSUE THREAD

**Issue by TBRC-TimB** [buda-base/drs-deposit#83]
Building Batches for the week of June 22- 27. Planning on two batches of 200 over the week.

**Comment by TBRC-TimB** [comment]
List containing the batches built this week. 

[batchlist0626.txt](https://github.com/buda-base/drs-deposit/files/4837634/batchlist0626.txt)

**Comment by jimk-bdrc** [comment]
Transferring to Druk started 26 June

**Comment by TBRC-TimB** [comment]
[batchlist0706.txt](https://github.com/buda-base/drs-deposit/files/4881115/batchlist0706.txt)

additional batches made the following week.

**Comment by TBRC-TimB** [comment]
Workflow modified. Closing these issues when batches are built.
