### ISSUE TITLE
Create DBApps method to update the processing db  works

### ISSUE THREAD

**Issue by jimk-bdrc** [buda-base/drs-deposit#98]
Add the sync date to the works table - existing works get an 'epoch start date' of 1/1/2020.

**Comment by jimk-bdrc** [comment]
subtask: create the 'processing'.'Works' table if not there. Columns:
workId - auto increment in
workName - text
size
file_count
sync_date: Date (don't bother with DATETIME)

**Comment by jimk-bdrc** [comment]
I wonder if you can reference tables in a different database?

**Comment by TBRC-TimB** [comment]
see https://github.com/buda-base/archive-ops/issues/221 related issue

**Comment by TBRC-Travis** [comment]
In terms of scope of what gets tracked it would be great if we could update the processing database for each step of our syncing/distribution process.  This would include distinct updates for when a volume is synced to:
- Amazon S3 (web images)
- RS5 Archive
- Internet Archive
- DRS

This would make it easy to query which works have reached our various archival endpoints.

**Comment by jimk-bdrc** [comment]
Defer, but move this work into DRS, where the migration audit logs will be put.

**Comment by TBRC-TimB** [comment]
fixed in https://github.com/buda-base/archive-ops/pull/342
